docker-deploy/web-app/RSVP/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('homepage/', views.EventHomepage, name='homepage'),
    path('create-event/', views.createEvent, name='create-event'),
    path('event-hompage/', views.EventHomepage, name='event-hompage'),

    path('owner-event/', views.OwnerEvent, name='event-owner'),
    path('guest-event/', views.GuestEvent, name='event-guest'),
    path('vendor-event/', views.VendorEvent, name='event-vendor'),

    path('owner/<int:event_id>/', views.ownerPage, name='owner-page'),
    path('vendor/<int:event_id>/', views.vendorPage, name='vendor-page'),
    path('guest/<int:event_id>/', views.guestPage, name='guest-page'),
    path('guestPlusOne/<int:event_id>/', views.guestPlusOnePage, name='guestPlusOne-page'),
    path('view-answer/<int:event_id>/', views.viewAnswerPage, name='view-answer-page'),
    path('invite/<int:event_id>/', views.invitePage, name='invite-page'),
    path('create-choice/<int:question_id>', views.createChoice, name='choice-create-page'),
    path('create-question/<int:event_id>', views.createQuestion, name='question-create-page'),
    path('finalize-question/<int:question_id>', views.finalizeQuestion, name='finalize-page'),
    path('free-text-response/<int:question_id>', views.freeText, name='free-text-page'),
    path('edit-question/<int:question_id>', views.editQuestion, name='question-edit-page'),
    path('edit-choice/<int:choice_id>', views.editChoice, name='choice-edit-page'),
    path('delete-question/<int:question_id>', views.deleteQuestion, name='question-delete-page'),
    path('delete-choice/<int:choice_id>', views.deleteChoice, name='choice-delete-page'),
    path('pendingPage/<int:role_id>', views.pendingPage, name='pendingPage'),
]

docker-deploy/web-app/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('RSVP/', include('django.contrib.auth.urls')), # include more?
    path('RSVP/', include('RSVP.urls')),
]

docker-deploy/web-app/RSVP/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.auth.models import User
from django.forms import ModelForm

# Create your models here.
class Event(models.Model):
    event_name = models.CharField(max_length=200)
    event_date = models.DateField()
    event_location = models.CharField(max_length=200)
    canPlusOne = models.BooleanField(default= False) # danger log
    def __str__(self):
        return self.event_name + '---' + self.event_date.__str__()+'---'+self.event_location

class Role(models.Model):
    Role_Choices = {
    ('vendor', 'vendor'),
    ('owner', 'owner'),
    ('guest', 'guest'),
    }
    event = models.ForeignKey(Event, on_delete = models.CASCADE)
    users = models.ManyToManyField(User)
    roleType = models.CharField(
        max_length = 100,
        choices = Role_Choices,
    )
    status = models.CharField(max_length = 100, default='pending') #accept, deny, pending
    def __str__(self):
        return self.roleType + '---' + self.event.event_name + '---' + self.status
    class Meta:
      ordering = ('roleType',)

class Question(models.Model):
    Question_Choices = {
    ('Free', 'Free Text Question'),
    ('Multi', 'Multiple Choice Question'),
    }
    question_text = models.CharField(max_length=200)
    event = models.ForeignKey(Event, on_delete = models.CASCADE)
    question_type = models.CharField(   #不选会怎么样？
        max_length = 100,
        choices = Question_Choices,
    )
    vendor_permission = models.BooleanField(default=True) # can vandor see
    finalization = models.BooleanField(default=False)
    def __str__(self):
        return self.question_text + '---' + self.question_type + '---' + self.vendor_permission.__str__()
    class Meta:
      ordering = ('question_text',)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
    class Meta:
      ordering = ('choice_text',)

class Response(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    question = models.ForeignKey(Question, on_delete = models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete = models.CASCADE)
    def __str__(self):
        return self.user.username + '---' + self.question.__str__() + '---' + self.choice.__str__()

docker-deploy/web-app/RSVP/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm, EmailField
from django.contrib.auth.forms import UserCreationForm
from .models import Event, Role, Choice, Question

class EventForm(ModelForm):
    class Meta:
        model = Event
        fields = '__all__'

class ChoiceForm(ModelForm):
    class Meta:
        model = Choice
        fields = ['choice_text']

class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = ['question_text', 'question_type', 'vendor_permission']

class editQuestionForm(forms.Form):
    question_text = forms.CharField(label="New Question Name", max_length=100)

class InviteForm(forms.Form):
    ROLE_CHOICES = (
    ("owner", ("owner")),
    ("vendor", ("vendor")),
    ("guest", ("guest")),
    )
    role = forms.ChoiceField(choices = ROLE_CHOICES, label="invite type", widget=forms.Select(), required=True)
    user_name = forms.CharField(label='user name', max_length=100)

class FinalizeForm(forms.Form):
    finalization = forms.BooleanField(label="finalize this question")

class TextForm(forms.Form):
    answer = forms.CharField(label="Free Text Answer here")

class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )


class pendingForm(forms.Form):
    STATUS_CHOICES = (
        ("accept", ("accept")),
        ("deny", ("deny"))
    )
    status = forms.ChoiceField(choices = STATUS_CHOICES, label="status type", widget=forms.Select(), required=True)

docker-deploy/web-app/RSVP/views.py
from django.shortcuts import render, redirect
from django import forms
from .forms import *
from django.shortcuts import get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.core.mail import send_mail

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, email = email, password=raw_password)
            login(request, user)
            return redirect('login')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})

@login_required
def EventHomepage(request):
    curUser = get_object_or_404(User, pk = request.user.id)
    pendingRoleSet = curUser.role_set.filter(status = 'pending')
    pendingNum = pendingRoleSet.count();
    return render(request, 'event-homepage.html', {'curUser': curUser, 'pendingNum':pendingNum})

@login_required
def OwnerEvent(request):
    curUser = get_object_or_404(User, pk = request.user.id)
    return render(request, 'event-owner.html', {'curUser': curUser})

@login_required
def GuestEvent(request):
    curUser = get_object_or_404(User, pk = request.user.id)
    return render(request, 'event-guest.html', {'curUser': curUser})

@login_required
def VendorEvent(request):
    curUser = get_object_or_404(User, pk = request.user.id)
    return render(request, 'event-vendor.html', {'curUser': curUser})

@login_required
def pendingPage(request, role_id):
    form = pendingForm(request.POST)
    curRole = get_object_or_404(Role, pk = role_id)
    if request.method == 'POST' and form.is_valid():
        toRemoveRole = Role.objects.get(roleType = curRole.roleType, event=curRole.event, status='pending')
        toRemoveRole.users.remove(User.objects.get(pk = request.user.id))
        toAddRole = Role.objects.get(roleType = curRole.roleType, event=curRole.event, status=form.cleaned_data['status'])
        toAddRole.users.add(User.objects.get(pk = request.user.id))
        curUser = get_object_or_404(User, pk = request.user.id)
        pendingNum = curUser.role_set.filter(status = 'pending').count();
        return render(request, 'event-homepage.html', {'curUser': curUser, 'pendingNum':pendingNum})
    else :
        return render(request, 'pendingPage.html', {'curRole':curRole, 'form':form})

@login_required
def ownerPage(request, event_id):
    curUser = get_object_or_404(User, pk = request.user.id)
    curEvent = get_object_or_404(Event, pk = event_id)
    role = Role.objects.get(roleType = 'owner', event = curEvent, status = 'accept')
    if curUser.role_set.filter(pk = role.pk).exists():
        return render(request, 'owner-page.html', {'curUser': curUser, 'curEvent':curEvent})
    else:
        return HttpResponseRedirect(reverse('event-hompage'))

@login_required
def vendorPage(request, event_id):
    curUser = get_object_or_404(User, pk = request.user.id)
    curEvent = get_object_or_404(Event, pk = event_id)
    role = Role.objects.get(roleType = 'vendor', event = curEvent, status = 'accept')
    if curUser.role_set.filter(pk = role.pk).exists():
        return render(request, 'vendor-page.html', {'curUser': curUser, 'curEvent':curEvent})
    else:
        return HttpResponseRedirect(reverse('event-hompage'))

@login_required
def guestPage(request, event_id): 
    curUser = get_object_or_404(User, pk = request.user.id)
    curEvent = get_object_or_404(Event, pk = event_id)
    role = Role.objects.get(roleType = 'guest', event = curEvent, status = 'accept')
    if not curUser.role_set.filter(pk = role.pk).exists():
        return HttpResponseRedirect(reverse('event-hompage'))
    else:
        if request.method == 'POST' :
            try:
                selected_choice = get_object_or_404(Choice, pk = request.POST['choice'])
                selected_choice.votes += 1
                selected_choice.save()
                if  Response.objects.filter(user = curUser, question = selected_choice.question).exists() :
                    if Response.objects.filter(user = curUser, question = selected_choice.question).count() == 1:
                        oldResponse = Response.objects.get(user = curUser, question = selected_choice.question)
                        oldResponse.choice.votes -= 1
                        oldResponse.choice.save()
                        oldResponse.choice = selected_choice
                        oldResponse.save()
                    else:
                        selected_choice.votes -= 1
                        selected_choice.save()
                        return render(request, 'guest-page.html', {'curUser': curUser, 'curEvent':curEvent,
                         'error_message':"You have already chosen to take +1, you can only edit in that page!!!"})
                else :
                    newResponse = Response.objects.create(user = curUser, question = selected_choice.question, choice = selected_choice)
                    newResponse.save()
                return render(request, 'guest-page.html', {'curUser': curUser, 'curEvent':curEvent})
            except(KeyError, Choice.DoesNotExist):
                return render(request, 'guest-page.html', {'curUser': curUser, 'curEvent':curEvent, 'error_message':"You did not seleet a valid choice"})
        else :
            return render(request, 'guest-page.html', {'curUser': curUser, 'curEvent':curEvent})
        


@login_required
def finalizeQuestion(request, question_id): 
    form = FinalizeForm(request.POST)
    curQuestion = get_object_or_404(Question, pk = question_id)
    if request.method == 'POST' and form.is_valid():
        finalizationStatus = form.cleaned_data['finalization']
        curQuestion.finalization = finalizationStatus
        # print(curQuestion.finalization)
        curQuestion.save()
        curUser = get_object_or_404(User, pk = request.user.id)
        return render(request, 'vendor-page.html', {'curUser': curUser, 'curEvent':curQuestion.event})
    else :
        form = FinalizeForm();
        curQuestion = get_object_or_404(Question, pk = question_id)
        return render(request, 'finalize-page.html', {'curQuestion':curQuestion , 'form':form})

@login_required
def viewAnswerPage(request, event_id): #
    curUser = get_object_or_404(User, pk = request.user.id)
    curEvent = get_object_or_404(Event, pk = event_id)
    curQuestionSet = curEvent.question_set.all()
    responseSet = set()
    for curQuestion in curQuestionSet :
        if Response.objects.filter(user = curUser, question = curQuestion).exists() :
            if Response.objects.filter(user = curUser, question = curQuestion).count() == 2 :
                curResponse1 = Response.objects.filter(user = curUser, question = curQuestion)[0]
                curResponse2 = Response.objects.filter(user = curUser, question = curQuestion)[1]
                responseSet.add(curResponse1)
                responseSet.add(curResponse2)
            else :
                curResponse = Response.objects.get(user = curUser, question = curQuestion)
                responseSet.add(curResponse)
    return render(request, 'view-answer.html', {'responseSet':responseSet})



@login_required
def guestPlusOnePage(request, event_id): #
    curUser = get_object_or_404(User, pk = request.user.id)
    curEvent = get_object_or_404(Event, pk = event_id)
    role = Role.objects.get(roleType = 'guest', event = curEvent, status = 'accept')
    if not curUser.role_set.filter(pk = role.pk).exists():
        return HttpResponseRedirect(reverse('event-hompage'))
    else:   
        if request.method == 'POST' :
            try:
                selected_choice1 = get_object_or_404(Choice, pk = request.POST['choice'])
                selected_choice2 = get_object_or_404(Choice, pk = request.POST['choiceplus'])
                if request.POST['choice'] == request.POST['choiceplus']:
                    selected_choice1.votes += 2
                    selected_choice1.save()
                else:
                    selected_choice1.votes += 1
                    selected_choice1.save()
                    selected_choice2.votes += 1
                    selected_choice2.save()
                if  Response.objects.filter(user = curUser, question = selected_choice1.question).exists():
                    if Response.objects.filter(user = curUser, question = selected_choice1.question).count() > 1:
                        oldResponse1 = Response.objects.filter(user = curUser, question = selected_choice1.question)[0]
                        oldResponse1.choice.votes -= 1
                        oldResponse1.choice.save()
                        oldResponse2 = Response.objects.filter(user = curUser, question = selected_choice1.question)[1]
                        oldResponse2.choice.votes -= 1
                        oldResponse2.choice.save()
                        oldResponse1.choice = selected_choice1
                        oldResponse1.save()
                        oldResponse2.choice = selected_choice2
                        oldResponse2.save()
                    else:
                        if request.POST['choice'] == request.POST['choiceplus']:
                            selected_choice1.votes -= 2
                            selected_choice1.save()
                        else:
                            selected_choice1.votes -= 1
                            selected_choice1.save()
                            selected_choice2.votes -= 1

docker-deploy/web-app/RSVP/templates/base.html
<!-- templates/base.html -->
<!-- Cited from: https://www.youtube.com/watch?v=-nvoGfTD4QU&index=28&list=PL6gx4Cwl9DGBlmzzFcLgDhKTTfNLfX1IK-->
<!--  -->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}RSVP{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'RSVP/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


</head>

<body>
	<nav class="navbar navbar-inverse ">
    <div class="container-fluid">
        <!-- Header -->
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'homepage' %}">Pending Event</a>
        </div>
        <!-- Items -->
        <div class="collapse navbar-collapse " id="topNavBar">
            

            <ul class="nav navbar-nav ">
                <li>
                    <a href="{% url 'event-owner' %}">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Owner Event
                    </a>
                </li>
            </ul>

            <ul class="nav navbar-nav ">
                <li>
                    <a href="{% url 'event-guest' %}">
                        <span class="glyphicon glyphicon-glass" aria-hidden="true"></span>&nbsp; Guest Event
                    </a>
                </li>
            </ul>

            <ul class="nav navbar-nav ">
                <li>
                    <a href="{% url 'event-vendor' %}">
                        <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>&nbsp; Vendor Event
                    </a>
                </li>
            </ul>


            <ul class="nav navbar-nav ">
                <li>
                    <a href="{% url 'create-event' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Create New Event
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'logout' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
	{% block content %}
    {% endblock %}
</body>
</html>

docker-deploy/web-app/RSVP/templates/create-event.html
{% extends 'base.html' %}
{% block title %}Event Creation Page{% endblock %}

{% block content %}
  	{% if error_message %}
        <div class="alert alert-danger">
          <strong>{{ error_message }}</strong>
        </div>
  	{% endif %}
	<h1>This is event creation page!</h1>
	<form action="" method="post">
	    {% csrf_token %}
	    <table>
	    {{form.as_p}}
	    </table>
	    <input type="submit" value="Submit" />
	</form>
{% endblock %}

docker-deploy/web-app/RSVP/templates/edit-choice.html
{% extends 'base.html' %}
{% block title %}Choice Edit Page{% endblock %}

{% block content %}

	<h1>This is the choice edit page</h1>
	<p><h2>The question: {{ choice.question.question_text }}</h2></p >
	<p><h3>The choice you want to edit: {{ choice.choice_text }}</h3></p >
	<p><a href="{% url 'choice-delete-page' choice.id  %}">Delete this choice?</a></p>
	<form action="" method="post">
	  	{% csrf_token %}
	  	<table>
	    	{{form.as_p}}
	  	</table>
	  	<input type="submit" value="Submit" />
	</form>


	<p><a href="{% url 'question-edit-page' choice.question.id  %}">Question page</a></p>

{% endblock %}

docker-deploy/web-app/RSVP/templates/event-guest.html
{% extends 'base.html' %}
{% block title %}Guest Event Homepage{% endblock %}

{% block content %}
  <h1>Dear {{curUser}}: </h1>
  <h3>Here is your event (as guest):</h3>
  <p><br></p>
    {% for role in curUser.role_set.all %}
      {% if role.roleType == "guest" and role.status == "accept"%}
        <p>Event name: {{ role.event.event_name }}</p >
        <p>Event date: {{ role.event.event_date }}</p >
        <p>Event location: {{ role.event.event_location }}</p >
        
        {% if role.event.canPlusOne == True %}
          <a href="{% url 'guest-page' role.event.id %}">I am going by my self!</a><br>
          <a href="{% url 'guestPlusOne-page' role.event.id %}">I am going with a +1!</a>
        {% endif %}
        {% if role.event.canPlusOne == False %}
          <a href="{% url 'guest-page' role.event.id  %}">I am going!</a><br>
        {% endif %}
        
        <p><br></p>
      {% endif %}
    {% endfor %}


{% endblock %}

docker-deploy/web-app/RSVP/templates/event-homepage.html
{% extends 'base.html' %}
{% block title %}Pending Event Homepage{% endblock %}

{% block content %}
  <h1>Dear {{curUser}}: </h1>
  <h3>You have {{pendingNum}} pending events: </h3>
  <p><br></p>
  
  {% for role in curUser.role_set.all %}
    {% if role.status == "pending"%}
      <p><a href="{% url 'pendingPage' role.id %}"> {{ role.event.event_name }}</a></p>
    {% endif %}
  {% endfor %}

{% endblock %}

docker-deploy/web-app/RSVP/templates/guest-page.html
{% extends 'base.html' %}
{% block title %}Gues Page{% endblock %}
{% block content %}

      <h1>This is guest page</h1>
      <p>Event name: {{ curEvent.event_name }}</p >
      <p>Event date: {{ curEvent.event_date }}</p >
      <p>Event location: {{ curEvent.event_location }}</p >
      <p><a href="{% url 'view-answer-page' curEvent.id %}"> view all your answers</a></p>
      {% if error_message %}
            <div class="alert alert-danger">
                  <strong>{{ error_message }}</strong>
            </div>
      {% endif %}


      <h2>These are multiple choice question: </h2>
      {% for question in curEvent.question_set.all %}
            {% if question.finalization == False and question.question_type == "Multi" %}
            <h3>Question: {{ question.question_text }}</h3>
            	<form action="" method="post">
            	{% csrf_token %}
            	{% for choice in question.choice_set.all%}
            		<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
            		<label for="choice{{ forloop.counter }}">
                              {# <img src = "https://i.imgur.com/b9b13Rd.png"> #}
                              {{ choice.choice_text }}
                        </label><br />
            	{% endfor %}
            	<input type="submit" value="Vote" />
      		</form>
            {% endif %}
      {% endfor %}

      <h2>These are free text question: </h2>
      {% for question in curEvent.question_set.all %}
            {% if question.finalization == False and question.question_type == "Free"%}
                  <p><a href="{% url 'free-text-page' question.id %}">{{question.question_text}}</a></p>
            {% endif %}
      {% endfor %}



      <h2>These question are finalized by vendor</h2>
      {% for question in curEvent.question_set.all %}
            {% if question.finalization == True %}
            <h2>Question: {{ question.question_text }}</h2>
            <p><br></p>
            {% endif %}
      {% endfor %}

      <!-- <p><a href="{% url 'homepage' %}">Homepage</a></p> -->
      <!-- <p><a href="{% url 'logout'%}">Logout</a></p> -->
{% endblock %}

docker-deploy/web-app/RSVP/templates/owner-page.html
{% extends 'base.html' %}
{% block title %}Owner Page{% endblock %}

{% block content %}

  <h1>This is the owner page</h1>
  <p>Event name: {{ curEvent.event_name }}</p >
  <p>Event date: {{ curEvent.event_date }}</p >
  <p>Event location: {{ curEvent.event_location }}</p >

  <h2>These are multiple choice question response:</h2>
  {% for q in curEvent.question_set.all %}
        {% if q.question_type == 'Multi' %}
        <h2>Question: {{ q.question_text }}</h2>
        <p><a href="{% url 'question-edit-page' q.id %}">Edit this questions?</a></p>
        	{% for c in q.choice_set.all%}
        		<h3>Choice: {{ c.choice_text }}</h3> 
        		<a>votes: {{ c.votes }}</a> 
        	{% endfor %}
        <p><br></p>
        {% endif %}
  {% endfor %}

  <h2>These are free text question response:</h2>
  {% for q in curEvent.question_set.all %}
        {% if q.question_type == 'Free' %}
        <h2>Question: {{ q.question_text }}</h2>
        <p><a href="{% url 'question-edit-page' q.id %}">Edit this questions?</a></p>
          {% for r in q.response_set.all%}
            <h3>{{r.user.username}}: {{ r.choice.choice_text }}</h3> 
          {% endfor %}
        <p><br></p>
        {% endif %}
  {% endfor %}

  <p><a href="{% url 'question-create-page' curEvent.id%}">Create new questions?</a></p>
  <p><a href="{% url 'invite-page' curEvent.id %}">Invite others in</a></p>

{% endblock %}

docker-deploy/web-app/RSVP/templates/signup.html
<!-- templates/signup.html -->

{% block title %}Sign Up{% endblock %}
{% block content %}

  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
    <a href="{% url 'home' %}">Home</a>
  </form>
  
{% endblock %}

docker-deploy/web-app/RSVP/templates/vendor-page.html
{% extends 'base.html' %}
{% block title %}Vendor Page{% endblock %}
{% block content %}
  <h1>This is the vendor page</h1>
  <p>Event name: {{ curEvent.event_name }}</p >
  <p>Event date: {{ curEvent.event_date }}</p >
  <p>Event location: {{ curEvent.event_location }}</p >

  <h1>These Question are finalized</h1>
  <h2>--------These are multiple choice question response--------:</h2>
  {% for q in curEvent.question_set.all %}
        {% if q.question_type == 'Multi' and q.vendor_permission == True and q.finalization == True%}
        <h2>Question: {{ q.question_text }}</h2>
          {% for c in q.choice_set.all%}
            <h3>Choice: {{ c.choice_text }}</h3> 
            <a>votes: {{ c.votes }}</a> 
          {% endfor %}
        <p><br></p>
        {% endif %}
  {% endfor %}

  <h2> --------These are free text question response--------:</h2>
  {% for q in curEvent.question_set.all %}
        {% if q.question_type == 'Free' and q.vendor_permission == True and q.finalization == True%}
        <h2>Question: {{ q.question_text }}</h2>
          {% for r in q.responce_set.all%}
            <h3>{{ r.choice.choice_text }}</h3> 
          {% endfor %}
        <p><br></p>
        {% endif %}
  {% endfor %}


  <h1>These Question are open</h1>
  <h2>--------These are multiple choice question response--------:</h2>
  {% for q in curEvent.question_set.all %}
        {% if q.question_type == 'Multi' and q.vendor_permission == True and q.finalization == False%}
        <h2>Question: {{ q.question_text }}</h2>
          {% for c in q.choice_set.all%}
            <h3>Choice: {{ c.choice_text }}</h3> 
            <a>votes: {{ c.votes }}</a> 
          {% endfor %}
          <p><a href="{% url 'finalize-page' q.id %}">finalize this question</a></p>
          <p><br></p>
        {% endif %}
  {% endfor %}

  <h2>--------These are free text question response--------:</h2>
  {% for q in curEvent.question_set.all %}
        {% if q.question_type == 'Free' and q.vendor_permission == True and q.finalization == False%}
        <h2>Question: {{ q.question_text }}</h2>
          {% for r in q.response_set.all%}
            <h3>{{ r.choice.choice_text }}</h3> 
          {% endfor %}
          <p><a href="{% url 'finalize-page' q.id %}">finalize this question</a></p>
        <p><br></p>
        {% endif %}
  {% endfor %}
  <!-- link to close curr event -->
  <!-- <p><a href="{% url 'homepage' %}">Homepage</a></p> -->
  <!-- <p><a href="{% url 'logout'%}">Logout</a></p> -->

{% endblock %}